/*
  # Create gyms table

  1. New Tables
    - `gyms`
      - `id` (bigint, primary key)
      - `name` (text) - gym name
      - `address` (text) - gym address
      - `active` (boolean) - whether gym is active
      - `created_at` (timestamp)

  2. Security
    - Enable RLS on `gyms` table
    - Add policy for public read access
    - Add policy for admin-only write access
*/

CREATE TABLE IF NOT EXISTS gyms (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  address text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE gyms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
  ON gyms
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Admins can manage gyms"
  ON gyms
  FOR ALL
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE users.auth_id = auth.uid() AND users.is_admin = true
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM users 
    WHERE users.auth_id = auth.uid() AND users.is_admin = true
  ));