/*
  # Create sports table

  1. New Tables
    - `sports`
      - `id` (bigint, primary key)
      - `name` (text, unique) - sport name
      - `description` (text) - sport description
      - `active` (boolean) - whether sport is active
      - `created_at` (timestamp)

  2. Security
    - Enable RLS on `sports` table
    - Add policy for public read access
    - Add policy for admin-only write access
*/

CREATE TABLE IF NOT EXISTS sports (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL,
  description text,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE sports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
  ON sports
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Admins can manage sports"
  ON sports
  FOR ALL
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM users 
    WHERE users.auth_id = auth.uid() AND users.is_admin = true
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM users 
    WHERE users.auth_id = auth.uid() AND users.is_admin = true
  ));

-- Insert default sports
INSERT INTO sports (name, description) VALUES
  ('Volleyball', 'Indoor and beach volleyball leagues'),
  ('Badminton', 'Recreational and competitive badminton leagues');