-- Ensure transfer history tables exist when running against older local clones
CREATE TABLE IF NOT EXISTS team_transfer_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  from_league_id BIGINT,
  to_league_id BIGINT,
  transferred_by UUID NOT NULL,
  transfer_reason TEXT,
  metadata JSONB,
  transferred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_team_transfer_history_team_id ON team_transfer_history(team_id);
CREATE INDEX IF NOT EXISTS idx_team_transfer_history_from_league ON team_transfer_history(from_league_id);
CREATE INDEX IF NOT EXISTS idx_team_transfer_history_to_league ON team_transfer_history(to_league_id);

-- Ensure the team_id FK exists (older dumps may lack it)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'team_transfer_history_team_id_fkey'
      AND conrelid = 'team_transfer_history'::regclass
  ) THEN
    ALTER TABLE team_transfer_history
      ADD CONSTRAINT team_transfer_history_team_id_fkey
      FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Ensure transfer history records don't block league deletion
ALTER TABLE team_transfer_history
  DROP CONSTRAINT IF EXISTS team_transfer_history_from_league_id_fkey;

ALTER TABLE team_transfer_history
  ADD CONSTRAINT team_transfer_history_from_league_id_fkey
  FOREIGN KEY (from_league_id)
  REFERENCES leagues(id)
  ON DELETE CASCADE;

ALTER TABLE team_transfer_history
  DROP CONSTRAINT IF EXISTS team_transfer_history_to_league_id_fkey;

ALTER TABLE team_transfer_history
  ADD CONSTRAINT team_transfer_history_to_league_id_fkey
  FOREIGN KEY (to_league_id)
  REFERENCES leagues(id)
  ON DELETE CASCADE;

ALTER TABLE individual_transfer_history
  DROP CONSTRAINT IF EXISTS individual_transfer_history_from_league_id_fkey;

ALTER TABLE individual_transfer_history
  ADD CONSTRAINT individual_transfer_history_from_league_id_fkey
  FOREIGN KEY (from_league_id)
  REFERENCES leagues(id)
  ON DELETE CASCADE;

ALTER TABLE individual_transfer_history
  DROP CONSTRAINT IF EXISTS individual_transfer_history_to_league_id_fkey;

ALTER TABLE individual_transfer_history
  ADD CONSTRAINT individual_transfer_history_to_league_id_fkey
  FOREIGN KEY (to_league_id)
  REFERENCES leagues(id)
  ON DELETE CASCADE;
